export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_REMOVE_ITEM2 = "CART_REMOVE_ITEM2";
export const CART_ADD_ITEM2 = "CART_ADD_ITEM2";

export const CART_PUSH_REQUEST = "CART_PUSH_REQUEST";
export const CART_PUSH_SUCCESS = "CART_PUSH_SUCCESS";
export const CART_PUSH_FAIL = "CART_PUSH_FAIL";
