export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const ALL_PRODUCT_CATEGORY_REQUEST = "ALL_PRODUCT_CATEGORY_REQUEST";
export const ALL_PRODUCT_CATEGORY_SUCCESS = "ALL_PRODUCT_CATEGORY_SUCCESS";
export const ALL_PRODUCT_CATEGORY_FAIL = "ALL_PRODUCT_CATEGORY_FAIL";
