export const SAVE_CUSTOMER_INFO = "SAVE_CUSTOMER_INFO";
export const SAVE_CHECKOUT_DELIVERY_INFO = "SAVE_CHECKOUT_DELIVERY_INFO";
export const SAVE_CHECKOUT_BILLING_INFO = "SAVE_CHECKOUT_BILLING_INFO";
export const SAVE_PROMO_CODE = "SAVE_PROMO_CODE";

export const CREATE_DELIVERY_ADDRESS_REQUEST = "CREATE_DELIVERY_ADDRESS_REQUEST";
export const CREATE_DELIVERY_ADDRESS_SUCCESS = "CREATE_DELIVERY_ADDRESS_SUCCESS";
export const CREATE_DELIVERY_ADDRESS_FAILURE = "CREATE_DELIVERY_ADDRESS_FAILURE";

export const CHECKOUT_CART_REQUEST = "CHECKOUT_CART_REQUEST";
export const CHECKOUT_CART_SUCCESS = "CHECKOUT_CART_SUCCESS";
export const CHECKOUT_CART_FAIL = "CHECKOUT_CART_FAIL";
