

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS ";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const GET_POPULATED_ORDER_REQUEST = "GET_POPULATED_ORDER_REQUEST";
export const GET_POPULATED_ORDER_SUCCESS = "GET_POPULATED_ORDER_SUCCESS ";
export const GET_POPULATED_ORDER_FAIL = "GET_POPULATED_ORDER_FAIL";