export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const CREATE_ADDRESS_REQUEST = "USER_ADDRESSES_REQUEST"; 
export const CREATE_ADDRESS_SUCCESS = "USER_ADDRESSES_SUCCESS";
export const CREATE_ADDRESS_FAIL = "USER_ADDRESSES_FAIL";

export const USER_ADDRESSES_REQUEST = "USER_ADDRESSES_REQUEST"; 
export const USER_ADDRESSES_SUCCESS = "USER_ADDRESSES_SUCCESS";
export const USER_ADDRESSES_FAIL = "USER_ADDRESSES_FAIL";