export const WISHLIST_CREATE_REQUEST = "WISHLIST_CREATE_REQUEST";
export const WISHLIST_CREATE_SUCCESS = " WISHLIST_CREATE_SUCCESS";
export const WISHLIST_CREATE_FAIL = " WISHLIST_CREATE_FAIL";

export const WISHLIST_GET_REQUEST = "WISHLIST_GET_REQUEST";
export const WISHLIST_GET_SUCCESS = " WISHLIST_GET_SUCCESS";
export const WISHLIST_GET_FAIL = " WISHLIST_GET_FAIL";

export const WISHLIST_UPDATE_REQUEST = "WISHLIST_UPDATE_REQUEST";
export const WISHLIST_UPDATE_SUCCESS = " WISHLIST_UPDATE_SUCCESS";
export const WISHLIST_UPDATE_FAIL = " WISHLIST_UPDATE_FAIL";

export const ONE_WISHLIST_GET_REQUEST = "ONE_WISHLIST_GET_REQUEST";
export const ONE_WISHLIST_GET_SUCCESS = " ONE_WISHLIST_GET_SUCCESS";
export const ONE_WISHLIST_GET_FAIL = " ONE_WISHLIST_GET_FAIL";

export const WISHLIST_DEL_REQUEST = "WISHLIST_DEL_REQUEST";
export const WISHLIST_DEL_SUCCESS = " WISHLIST_DEL_SUCCESS";
export const WISHLIST_DEL_FAIL = "WISHLIST_DEL_FAIL";

export const WISHLIST_DEL_ITEM_REQUEST = "WISHLIST_DEL_ITEM_REQUEST";
export const WISHLIST_DEL_ITEM_SUCCESS = " WISHLIST_DEL_ITEM_SUCCESS";
export const WISHLIST_DEL_ITEM_FAIL = "WISHLIST_DEL_ITEM_FAIL";
export const WISHLIST_DEL_ITEM_FROM_WISHLIST_REQUEST = "WISHLIST_DEL_ITEM_FROM_WISHLIST_REQUEST";
export const WISHLIST_DEL_ITEM_FROM_WISHLIST_SUCCESS = " WISHLIST_DEL_ITEM_FROM_WISHLIST_SUCCESS";
export const WISHLIST_DEL_ITEM_FROM_WISHLIST_FAIL = "WISHLIST_DEL_ITEM_FROM_WISHLIST_FAIL";
