export const WISHLIST_CREATE_REQUEST = "WISHLIST_CREATE_REQUEST";
export const WISHLIST_CREATE_SUCCESS = " WISHLIST_CREATE_SUCCESS";
export const WISHLIST_CREATE_FAIL = " WISHLIST_CREATE_FAIL";

export const WISHLIST_GET_REQUEST = "WISHLIST_GET_REQUEST";
export const WISHLIST_GET_SUCCESS = " WISHLIST_GET_SUCCESS";
export const WISHLIST_GET_FAIL = " WISHLIST_GET_FAIL";

export const WISHLIST_UPDATE_REQUEST = "WISHLIST_UPDATE_REQUEST";
export const WISHLIST_UPDATE_SUCCESS = " WISHLIST_UPDATE_SUCCESS";
export const WISHLIST_UPDATE_FAIL = " WISHLIST_UPDATE_FAIL";
